function [fitresult, gof] = createFity(VarName2, VarName1)
%CREATEFIT(VARNAME2,VARNAME1)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : VarName2
%      Y Output: VarName1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Apr-2020 15:32:58


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( VarName2, VarName1 );

% Set up fittype and options.
ft = fittype( '(a^b*(1/x-1))^(1/b)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.0975404049994095 0.278498218867048];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'VarName1 vs. VarName2', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'VarName2', 'Interpreter', 'none' );
ylabel( 'VarName1', 'Interpreter', 'none' );
grid on


